name: Exoplanets Pipeline

on:
  schedule:
    - cron: '0 8 * * *'  # todos los días 8am UTC
  workflow_dispatch:       # para correrlo manualmente desde GitHub

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run pipeline
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        run: python main.py

  transform:
    needs: extract
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dbt dependencies
        working-directory: exoplanets
        run: pip install -r requirements-dbt.txt
      - name: Generate profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat << EOF > ~/.dbt/profiles.yml
          exoplanets:
            target: dev
            outputs:
              dev:
                type: duckdb
                path: exoplanets.duckdb
                extensions:
                  - httpfs
                settings:
                  s3_region: "${{ secrets.AWS_REGION }}"
                  s3_access_key_id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
                  s3_secret_access_key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          EOF

      - name: Run dbt
        working-directory: exoplanets
        run: dbt run

      - name: Run dbt tests
        working-directory: exoplanets
        run: dbt test

      - name: Upload duckdb to S3
        working-directory: exoplanets
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 cp exoplanets.duckdb s3://${{ secrets.AWS_BUCKET_NAME }}/warehouse/exoplanets.duckdb

      - name: Instalar dependencias de export
        run: pip install duckdb pandas boto3 --break-system-packages

      - name: Exportar marts a JSON
        working-directory: exoplanets
        run: python export/export_marts.py
        env:
          DUCKDB_PATH: exoplanets.duckdb

      - name: Subir JSON a S3 (carpeta pública)
        run: python export/upload_to_s3.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}